name: environment variables Demo

on:
  push:

env:
  APP_NAME: flask-pp

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
 
      - uses: actions/checkout@v4

      -  name: print variables
         run: echo $APP_NAME
