name: Flask CI Pipeline

on:
  push:

env:
  IMAGE_NAME: joeh91/library
  IMAGE_TAG: V8

jobs:
  test:
    runs-on: ubuntu-latest
      steps:
        - name: checking code
          uses: actions/checkout@v4
        
        - name: setup python
          uses: actions/setup-python
          with:
            python-version: "3.12"


        - name: installing dependencies
          run: pip install -r requirements.txt

        - name: lint testing
          run: flake8 .
 
        - name: compiling
          run: python -m py_compile app.py

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ DOCKER_USERNAME }}
          password: ${{ DOCKER_PASSWORD }}

      - name: building image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: docker push
        run: docker push $IMAGE_NAME:$IMAGE_TAG
   
    
      
